### ISSUE TITLE
Move to vuepress

### ISSUE THREAD

**Issue by tiziodcaio** [thundernest/developer-docs#116]
https://vuepress.github.io

**Comment by Alecaddd** [comment]
Please,a void opening issues without any explanation, proper examples, or in this case, a valid a concrete reason for adopting vuepress.

Closing this issue as it's invalid and not useful.
We can reopen it later if necessary.

**Comment by tiziodcaio** [comment]
@Alecaddd Sorry I didn't want to irritate you... Otherwise, I think that the issue can stay closed due to gitbook still a valid platform.
Simply I wanted to propose to use vuepress to deploy the markdown guide, I can do it and sincerely sometimes is better than vuepress.
Bye and sorry for making this stupid beginner error.

**Comment by ryanleesipes** [comment]
Hey @tiziodcaio it's actually a neat project. @Alecaddd has a good point, but I actually appreciate what you shared. Next time just let us know what you are proposing and why.

**Comment by tiziodcaio** [comment]
> Hey @tiziodcaio it's actually a neat project. @Alecaddd has a good point, but I actually appreciate what you shared. Next time just let us know what you are proposing and why.

Ok, so I can make an other issue more clear or modify this one...

**Comment by Sancus** [comment]
I'm not really sure what the request here was? Vuepress just looks like a JS static site generator. It doesn't serve the same purpose as Git Book. And if we did want to change our documentation platform(we don't, right now), there would need to be quite a lot of other options considered first.

**Comment by tiziodcaio** [comment]
Ok sure no problem ☺️
