### ISSUE TITLE
wrong link to mozilla-central hg in build instructions?

### ISSUE THREAD

**Issue by opto** [thundernest/developer-docs#123]

**Comment by opto** [comment]
here:
https://github.com/thundernest/developer-docs/blob/master/thunderbird-development/building-thunderbird/windows-build-prerequisites.md

is this:  hg clone https://hg.mozilla.org/mozilla-central source/

giving a 404 on clone in several hg tools..

from here: https://hg.mozilla.org/
it looks like it means  hg clone https://hg.mozilla.org/mozilla-central/?

at least, tortoisehg and another hg tools cannot clone what is given on the page, and not everybody uses command line hg, which might work or not.

**Comment by jobisoft** [comment]
Opto, those are both the same urls. The "source/" part is the second parameter to the clone command.

**Comment by ryanleesipes** [comment]
It's true @opto - the source part is the directory to clone the repo into.
