### ISSUE TITLE
TB 78->91 page missing: Change of subfolder attribute of nsIMsgFolder

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#126]
This happened before TB 86:

https://bugzilla.mozilla.org/show_bug.cgi?id=1682941

Now, the [the TB 78->91 changes page](https://developer.thunderbird.net/add-ons/updating/tb91/changes) does mention a change to nsIMsgFolder.subFolders - but not the correct change. The change isn't abandoning nsISupportsArray in favor of a JS array, but rather replacing nsISimpleIterator with nsIArray.

See also #127.

**Comment by jobisoft** [comment]
I rephrased that section. I made it clear that subFolders now returns a simple array.

**Comment by eyalroz** [comment]
@jobisoft : It's an `nsIArray`... is that always interpreted as a plain JS array?

**Comment by jobisoft** [comment]
For the JS interface it is an array:
https://searchfox.org/comm-central/source/mailnews/base/public/nsIMsgFolder.idl#667

Or is it not?
