### ISSUE TITLE
TB 78->91 page missing: message copy service method name change

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#127]
The nsIMessageCopyService interface has had methods renamed to start with lowercase letters:

https://bugzilla.mozilla.org/show_bug.cgi?id=1715433

and while the service is mentioned on the [TB 78->91 page](https://developer.thunderbird.net/add-ons/updating/tb91/changes), that's only in context of the switch to JS arrays.

Was a full pass made over the mercurial log to make sure all the changes covered by the page?

**Comment by jobisoft** [comment]
I added an extra section to cover the rename.

> Was a full pass made over the mercurial log to make sure all the changes covered by the page?

I did spend a huge amount of time searching for changes, but doing a full pass over the mercurial log and finding all relevant changes for add-on authors is not something I am capable of doing. I would not have time for other tasks. In general, we document changes as we encounter them or if someone is informing us.

I did not know of the other renames, will add them later, logging them here:

nsIMsgCopyService::copyMessages()
nsIMsgCopyService::copyFileMessage()
notifyCompletion

**Comment by eyalroz** [comment]
> I did spend a huge amount of time searching for changes, but doing a full pass over the mercurial log and finding all relevant changes for add-on authors is not something I am capable of doing.

Fair enough, no complaint here.

However... if that doesn't happen, then developers making commits change APIs could conceivably mark them, or perhaps mark the relevant Bugzilla pages, to notify you to have a look for writing the update page for the next release. That should not be a significant burden for them, on one hand, and would lesser the load on you, on the other.
