### ISSUE TITLE
Need cause for recommendation to not have install.rdf+install.js

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#13]
In the TB 68 extension update docs, it says:

>  It is possible to have both `install.rdf` and `manifest.json` files in your extension, so you could release a version compatible with Thunderbird 60 and 68. It is **not recommended.**

This is a pretty significant statement to make: You're recommending extension authors drop compatibility with v60 and earlier when updating their extensions for 68... I really feel you should give a reason for this dis-recommendation.

**Comment by darktrojan** [comment]
I wrote this.

Hopefully by now your extension that runs in version 60 is stable and with minimal maintenance required. There's a large number of _significant_ changes most extensions will need for compatibility with 68, and we all know that making changes unintentionally leads to more problems. If your version for 60 isn't broken, don't fix it.

You can have two versions with different Thunderbird compatibilities at the same time. The add-ons site has been modified to support this. By default it (currently) shows the latest extension version compatible with 60, unless you visit it from 68.

That all said, it is up to you.

**Comment by eyalroz** [comment]
@darktrojan : First of all - the place for your elaboration is the Wiki, not this issue page...

To the point, though,

> Hopefully by now your extension that runs in version 60 is stable and with minimal maintenance required. 

Not necessarily. That is, there are a bunch of things I would like to do with the extension which are relevant to version 60 and much earlier versions. In general these could be either bug fixes, cosmetic/graphic changes or new features.

> There's a large number of _significant_ changes most extensions will need for compatibility with 68, and we all know that making changes unintentionally leads to more problems. If your version for 60 isn't broken, don't fix it.

I don't understand that paragraph. There is no such thing as "my version for 60". I have one version of the extension for all Thunderbird versions I support, and I intend to keep it that way - unless there's a very good reason not to. When something in Thunderbird changes in a way which makes my existing code break, I usually do something like `if (check_tb_version_somehow() > 123) { do one thing} else {do another thing}` or `try { do_things_the_new_way } catch(ex) { if (we_failed_since_new_way_doesn't_work) { do_things_the_old_way} else { throw(ex); }`.

> You can have two versions with different Thunderbird compatibilities at the same time. 

Why would I want to maintain two versions of my extension?

**Comment by mkmelin** [comment]
You probably aren't doing your users any service by that. What's the point? Update, and you get the new functionality - like any other software. Instead you'd be risking that the functionality is broken in one of the versions. Up to you of course, but clearly nothing I'd recommend. You're talking about maybe two-three months of overlap before EOL anyway.

Agreed we should add the explanation to the documentation. I'd call that officially unsupported (meaning any issues with it should be marked WONTFIX.)

**Comment by jobisoft** [comment]
@eyalroz : No one is forcing you to follow Geoffs suggestion. If you have the time and the resources to go the extra mile and update your addon so that it stays backward compatible (that also involves testing it on older TB versions) you are free to do so.

Myself, I decided to not do that, so the current version of my add-on on ATN is only compatible with TB60 and as soon as TB68 beta is out, I will upload a "new" version, which is only compatible with TB68. That way all the changes I had to apply to the TB68 Version have no effect on my TB60 users. That is what Geoff was talking about and I fully agree.

Furthermore, the add-on update documentation we are currently working on should help authors to update there add-ons with minimal efforts. If you recall the discussions on the mailing list, the most dominant complain about the required changes was "taking lots of time". I do not want to make it even more complicated by explaining quirks on how to get it run in TB60 and TB68.

Christopher Leidigh is working on a separate documentation for that. We might link to it from the main guide, if there are no objections.

**Comment by eyalroz** [comment]
> You probably aren't doing your users any service by that. What's the point? Update, and you get the new functionality

Update _the extension_, not Thunderbird. I don't control which version of Thunderbird people use. Some work on older systems / older distributions.

> - like any other software. 

On the contrary. Most application software, which is not intended for a build from source, makes an effort to be compatible not only with the latest and greatest operating system being used, but rather compatible much farther back - as much as is reasonable without bending over backwards. But - you know this. I mean, does Thunderbird require Windows 10 or Linux distributions based on kernel 5.x ? Of course not. IIANM, Windows XP is still supported (maybe even Windows 2000?)

**Comment by mkmelin** [comment]
Windows has its own set of baggage out of necessity. But it's hardly fruitful to compare applications to operating systems. 

There is no valid reason for someone to stay on an older release (beyond the 2-3m) - and that is indeed unsupported and very much discouraged.

**Comment by eyalroz** [comment]
> Windows has its own set of baggage out of necessity. But it's hardly fruitful to compare applications to operating systems.

I was comparing extensions to applications, not apps to OSes.

> There is no valid reason for someone to stay on an older release

It doesn't matter wheter you (or even me) believe the reasons to be "valid" or not. It's just a reality that a lot of users use older versions. At any rate, we don't even have to take the discussion to these extremes. Version 31.0 is not even 6 years old. That's still pretty new. So assume I just want to support relatively-new versions - my point is the same.

**Comment by mkmelin** [comment]
Version 52 is around 3% of users now (and other versions even less). It's a myth that "a lot" of users use older versions.

**Comment by jobisoft** [comment]
How about changing the alert box a bit?  Currently it states:

> Even though you _can_ write code compatible with both Thunderbird 60 and Thunderbird 68, it is _not_ recommended.

How about:

> Even though you _can_ write code compatible with both Thunderbird 60 and Thunderbird 68, it is _not_ suggested for the following reasons:
> * The amount of changes is huge and some changes are incompatible with TB60 so it will require extra steps to ensure the modified version compatible with TB68 also runs with TB60. You may actually break your add-on for TB60 users by releasing a backward compatible version for TB68 ("Do not fix something, that is not broken").
> * We think the time and resources needed to code and test backward compatible add-ons is not justified by the small amount of users running older versions of Thunderbird
> If you do want to stay backward compatible, you will find useful information here (link to Christopher's repository)
>

**Comment by eyalroz** [comment]
@jobisoft : This is a good practical suggestion. That is, without the authors changing their position on this matter, it clarifies things lets the reader make up their own mind.

**Comment by cleidigh** [comment]
@jobisoft 
I like this also.  I think strikes the appropriate tone.  We can use Thunderstorm as a clearinghouse for the type of information we don't want to mainstream it will be relegated to those developers intent on dual support and not confuse others.

**Comment by ryanleesipes** [comment]
@jobisoft I think your proposed language here is good!

**Comment by ryanleesipes** [comment]
This has been adjusted with: https://github.com/thundernest/developer-docs/commit/84c1c3bd6788bc35fdf8f2c87bc0a6d2a22d5689

Closing issue.
