### ISSUE TITLE
Typo on Adapt to Changes in Thunderbird 69-78 page

### ISSUE THREAD

**Issue by dillenger** [thundernest/developer-docs#134]
In the `<textbox>` paragraph on https://github.com/thundernest/developer-docs/blob/master/add-ons/updating/tb78/changes.md
`<script src="chrome://global/content/editMenuOverlay.js.js"/>`
should be
`<script src="chrome://global/content/editMenuOverlay.js"/>`

**Comment by jobisoft** [comment]
Thanks for reporting. Fixed.
