### ISSUE TITLE
Dead links in developer documentation about E-mail autoconfiguration

### ISSUE THREAD

**Issue by jhaand** [thundernest/developer-docs#156]
Hi,

I tried to write an XML file or the autoconfig in Thunderbird this morning. Getting to the documentation proved a bit troublesome. 

The file format is decribed at: 
https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat

Which contains the following dead links:
[Description of the different mechanisms to serve the configuration file](https://developer.mozilla.org/en/Thunderbird/Autoconfiguration) 
[How to create your own config file](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo)

I was able to retrieve them via archive.org

Could you fix the content?

**Comment by jobisoft** [comment]
Those pages have been purged by Mozilla. The first one is in this backup:
https://udn.realityripple.com/docs/Mozilla/Thunderbird/Autoconfiguration

But the second one is only in the archives:
https://web.archive.org/web/20200915064941/https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo

The content should probably be re-added to the wiki page, If it is only used by Thunderbird, the entire section should be added to DTN.

**Comment by SphinxKnight** [comment]
adding https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/thunderbird/autoconfiguration to pointers
