### ISSUE TITLE
Missing code in "hello-world" extension tutorial

### ISSUE THREAD

**Issue by soundlake** [thundernest/developer-docs#169]
Thank you for the good documents, first of all.

This is where I found the problem: https://developer.thunderbird.net/add-ons/hello-world-add-on#popup.js

The code is only 

> ```
> console.log('Hello, World! - from popup.js');
> ```

But it says

> What our little script does is sending a message to the console each time we click on our "Hello World" toolbar button.

In my humble opinion, there is no click event listener. It is supposed to be something like ...

```js
document
    .getElementsByClassName('popup-page')
    .item(0)
    .addEventListener(
        'click',
        () => console.log('Hello, World! - from popup.js')
    );
```

**Comment by jobisoft** [comment]
Hi!

The clickListener is not needed, because the `popup.js` script is executing its file scope code when the popup is shown (which happens if you click on the browser acrtion button). This is due to tha fact, that `popup.html` is loading `popup.js`.

**Comment by soundlake** [comment]
It's my bad. 🙈 I misunderstood clicking the "Hello World" text in the popup instead of the toolbar button.

Thank you for clarifying it.

**Comment by jobisoft** [comment]
No problem. Feel free to reach out using your communication channels to get more support if needed:
https://developer.thunderbird.net/add-ons/community
