### ISSUE TITLE
content listing on right side of page does not have scroll bar

### ISSUE THREAD

**Issue by opto** [thundernest/developer-docs#17]
this page: https://developer.thunderbird.net/add-ons/upgrading-add-ons-for-tb68/list-of-changes-in-thunderbird-core#changed-api    has a list of contents on the right side. It is truncated on a small screen ( 10 in) and there is no scroll bar.

**Comment by jobisoft** [comment]
Can you file a bug on gitbook about this?

**Comment by opto** [comment]
I am willing, but how/where/how to get login

**Comment by jobisoft** [comment]
https://docs.gitbook.com/faq#how-can-i-report-bugs

Thanks.

**Comment by Alecaddd** [comment]
This seems to be fixed for me.
@opto do you still see the problem?

**Comment by ryanleesipes** [comment]
It looks like this has been fixed, but it is also an issue with the platform we are using and not something we can directly change. Marking this closed.
