### ISSUE TITLE
change in addon code required since 60.6.1, not since 67, please correct

### ISSUE THREAD

**Issue by opto** [thundernest/developer-docs#18]
importing js:
var { Foo } = Cu.import("resource://foo/modules/Foo.jsm", null);

this is now necessary already in 60.6.1. Documentation says it was added in TB 67

**Comment by opto** [comment]
see pull request

**Comment by jobisoft** [comment]
I cannot confirm this. The old syntax is still working with 60.6.1, for XUL overlay addons as well as for bootstrapped addons. 

I have not tried, if the new syntax works in TB 60.6.1, but that would be beyond the guide anyhow, as we are only documenting what is breaking in TB68 and must be changed.

Maybe you see some other issue?
