### ISSUE TITLE
manifest.json not parsed correctly

### ISSUE THREAD

**Issue by amineallani** [thundernest/developer-docs#26]
I have developed a bootstrap add-on which was previously working on thunderbird v60. In order to make it compatible with the new thunderbird version ( currently testing on 67 beta ), i stared by changing the install.rdf file ( which was working fine on version 60 ) to a manifest.json file.

My manifest.json looks like the following:
```
{
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "smartmail@fra-uas.de",
      "strict_min_version": "67.0a1"
    }
  },
  "name": "SmartMail",
  "description": "",
  "version": "2.0",
  "author": "[amine]",
  "legacy": {
    "type": "bootstrap",
    "options": {
      "page": "",
      "open_in_tab": true
    }
  },
  "icons": {
    "64": "chrome/content/images/unisex32.png",
    "32": "chrome/content/images/unisex32.png",
    "16": "chrome/content/images/unisex32.png"
  }
}
```
However, when i try to install the extension (add-ons --> debug add-on), i get the following error message:
> Reading manifest: Error processing legacy: Value must either: be a boolean, or not contain an unexpected "type" property

**Comment by jobisoft** [comment]
That part of the guide was written for Thundebird 68. TB67 (the current Beta) indeed does not yet support the type attribute. 

Until a Beta for Thunderbird 68 is out, you can use the latest Nightly Build for TB68 to test your changes:
https://developer.thunderbird.net/add-ons/tb68#testing-thunderbird-68
However that has its UI broken.

We are all waiting for the Beta 68 :-)

**Comment by jobisoft** [comment]
@ryanleesipes: This issue could be a reason to postpone the general email to all add-on devs. 
If there is no official TB68 release, they cannot test their changes.

**Comment by amineallani** [comment]
@jobisoft Thank you for your reply. I guess it makes more sense then to wait for 68.

**Comment by jobisoft** [comment]
I just learned, that we have beta candidates now:
http://ftp.mozilla.org/pub/thunderbird/candidates/68.0b1-candidates/

I updated the documentation as well.

**Comment by kewisch** [comment]
Note the candidates shouldn't be widely advertised. The impatient can download them, but others should get the real thing.

**Comment by jobisoft** [comment]
I remove the link, if you say so. But the current situation is "not good" we cannot update our addons and test it, because we do not have a valid target. Many things needed for TB68 break TB67.

Before I linked the candidates (which is working good) I linked to the last TB68 daily and I think going back to that is making things worse.

What is your final call?

**Comment by kewisch** [comment]
We just need to get better at building betas. If Wayne and Jörg are fairly certain this will be the final then I guess it is ok. Best double check that the candidates will auto-update to the real beta, otherwise folks will be stuck on the candidate until the next beta

**Comment by jobisoft** [comment]
On maildev list Jörg said:

> I think they auto-update to, but only to the next 68 beta version, so you stay on 68 for your testing.

So we should be good?

**Comment by kewisch** [comment]
Best clarify what "next" means. My understanding is they have the version number 68.0b1, so the version check will only update to 68.0b2, not a new 68.0b1 candidate.

**Comment by jobisoft** [comment]
I thinkl I will not get closer to "I think so" :-)

I added a big info box to the doc.
https://developer.thunderbird.net/add-ons/tb68#testing-thunderbird-68

**Comment by clokep** [comment]
These betas should be released "soon", I'd recommend not being impatient here and letting the process do it's job.

**Comment by jobisoft** [comment]
@amineallani : I do not know if you have seen it, but the beta is out and you can actually test you add-on now against an official version. Happy testing :-)
