### ISSUE TITLE
Add new NotificationBox documentation

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/developer-docs#31]
We need to update the docs in order to reflect the new `NotificationBox` implementation based on the abstract class available from toolkit.

An initial reference is here: https://thunderbird.topicbox.com/groups/addons/T321f9b5d0964e424-Ma3ec42bc020def36c8745dd0

**Comment by jobisoft** [comment]
I have this scheduled for tomorrow.

**Comment by jobisoft** [comment]
@Alecaddd : Could you have a look at 
https://developer.thunderbird.net/add-ons/tb68/changes#less-than-notificationbox-greater-than

What happens, if the addon author wants to add a notification to a window, that does not have a notification box?

**Comment by Alecaddd** [comment]
Great, thanks for taking care of this.
Notifications can be added almost anywhere as far as there's a container with an `ID` to use as a target.

Eg.
```
const myNotification = {};
XPCOMUtils.defineLazyGetter(myNotification, "notificationbox", () => {
    return new MozElements.NotificationBox(element => {
        element.setAttribute("flex", "1");
        document.getElementById("targetID").append(element);
    });
});
```

At that point, the developer can use `myNotification.notificationbox` to append his own notifications.

**Comment by jobisoft** [comment]
Wow! Would it then be the better "update strategy" to just rename the <notificationbox> to <hbox> in my code and do the above in JS? This way I do not have to search for the correct box?

Or should authors use the default notification box of messenger and composer? And the above is just for custom dialogs?

**Comment by RealRaven2000** [comment]
I knew that something like this should be possible - that JavaScript is something an average Add-on author would not be able to come up with so we definitely should add this to the documentation. I will try this out on my Add-on quickFilters where I currently show a notification panel in the filters dialog. The old overlay contained:

```
<panel id="quickFilterNotification" noautohide="true">  
  <notificationbox flex="1" id="quickFilterNotificationBox" >
    <!-- <notification type="warning" label="Test" id="quickFiltersNotificationContent"/> -->
  </notificationbox>
</panel>
```

and this was the main js code for displaying the notification:

```
util.popupAlert(
  util.getBundleString('quickfilters.debug.fixFilters.result','{0} filters were fixed.').replace('{0}',countFixed),
  "quickFilters", "debug-success.png", 0
);


popupAlert: function popupAlert(text, title, icon, timeOut) {
  try {
    let isTimeout = !(timeOut == 0);
    if (!timeOut) timeOut = 4000;
    let panel = document.getElementById('quickFilterNotification');
    if (panel) {
      panel.openPopup(null, "after_start", 0, 0, false, false);
      let notificationBox = document.getElementById('quickFilterNotificationBox'),
          priority = notificationBox.PRIORITY_WARNING_MEDIUM,
          note = notificationBox.appendNotification( text , null , icon , priority, null, null ); 
      notificationBox.addEventListener('alertclose', function() { alert('test'); });
      if (isTimeout)
        window.setTimeout(function() {try{notificationBox.removeNotification(note)}catch(e){};panel.hidePopup();}, timeOut);
    }
    else {
      let prompts = Components.classes["@mozilla.org/embedcomp/prompt-service;1"]
                                    .getService(Components.interfaces.nsIPromptService);
      prompts.alert(window, title, text); 
    }
  }
  catch(e) {
    alert(text);
  }
}
  
```

**Comment by Alecaddd** [comment]
@jobisoft, it really depends on the situation, but using built-in notification ensures visual consistency and style.

**Comment by Alecaddd** [comment]
@RealRaven2000 Indeed, documenting this approach would be very useful for add-on developers.
It's a pretty easy implementation that depends on importing the `XPCOMUtils` object

**Comment by jobisoft** [comment]
I am sorry, I forgot about this one. I added it to the documentation.
