### ISSUE TITLE
[Code Example] Add menu item in new App Menu

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/developer-docs#35]
The new App Menu is part of daily now, so we should consider writing down a small tutorial on how to generate and append custom `menuitems` inside the various sections, and how to create sliding subsections.

**Comment by ryanleesipes** [comment]
I have updated the tutorial. An additional tutorial could do more complicated things. There is now an "Examples" section in the docs. We should fill that up.

**Comment by Alecaddd** [comment]
Great stuff, this can be closed.
