### ISSUE TITLE
Add Linting section

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/developer-docs#39]
We should add a section dedicated to the Linting of the code before pushing a patch, listing the commands and some formatting example.

Since we're adopting Prettier we should also list all the available extensions for the most commonly used code editors and IDEs.

**Comment by Alecaddd** [comment]
Hey @PaulMorris, if you have time or any capacity later next week, it would be awesome if you could take care of this.
I think that you might be the best person to handle it.
No rush, and a very low low priority on this.

**Comment by PaulMorris** [comment]
Hey @Alecaddd , yeah, I can try to get to this this week.

**Comment by PaulMorris** [comment]
Here's a PR I opened for this issue: https://github.com/thundernest/developer-docs/pull/44

**Comment by Alecaddd** [comment]
Sweet.
You can add "Fixes #39" in the commit message of your PR to automatically close this issue once it gets merged.
Not a big deal anyway
