### ISSUE TITLE
Add <textbox> to <html:input> conversion quick guide. 

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/developer-docs#50]
Now that daily is free of `<textbox>` elements, it might be helpful to write down a quick HOW-TO guide for add-on developers who might need to do the same.

Here's everything I learned while working on this:

- Add `aria-labelledby="labelID"` to the `html:input` for accessibility.
- All the proper styles and classes should come from the `input-fields.css`, most likely all the various cases should be covered by those CSS declarations.
- Use the class `.input-container` on an `HBOX` when you need the input field to behave like a `flex="1"` as the attribute `flex=""` doesn't do anything on the input field, so it can/must be removed.
- Add the `globalOverlay.js` and `editMenuOverlay.js` if the right click (context menu) doesn't work on an input field.
- Specify the field type, like `type="text"`, `type="number"`, etc.
- Visually compare the fields before and after the conversion to be sure the UI, sizing, and spacing doesn't change.
- Always look if any JS method is interacting with the fields you're updating to check if the `textbox` tag name is used for conditions or similar. Eg. `if (element.localName == "textbox") {` or `getElementsByTagName("textbox")`

**Comment by jobisoft** [comment]
If you want, you can assign that to me and I will take care of this next week.

**Comment by Alecaddd** [comment]
@jobisoft that'd be sweet, thank you so much.

**Comment by jobisoft** [comment]
Sorry that it took so long:
https://developer.thunderbird.net/add-ons/tb78/changes#less-than-textbox-greater-than

I still need help with `aria-labelledby=".."`. Was that a supported parameter of the `textbox `and we can simply use it with `html:input` as well?

**Comment by Alecaddd** [comment]
The `textbox` didn't need that because the `label control="textboxID"` was taking care of applying the label name to the textbox field for accessibility purpose.
The simple `html:input` field doesn't inherit the label name from the `control` attribute, so it needs the `aria-labelledby` to reference the label ID.

**Comment by mkmelin** [comment]
Looks like the bug to make the a11y association automatic is now fixed. https://bugzilla.mozilla.org/show_bug.cgi?id=1572677

**Comment by jobisoft** [comment]
@mkmelin : That means control values of labels are now enough and we do not need the aria-labelledby anymore?

**Comment by mkmelin** [comment]
I think so. We might want to get it verified.

**Comment by mkmelin** [comment]
Asked in the bug, and we indeed do not need it anymore.

**Comment by jobisoft** [comment]
Thanks, than I have all the needed parts on DTN.
