### ISSUE TITLE
Blog header link different from main site

### ISSUE THREAD

**Issue by camporter** [thundernest/developer-docs#58]
Really minor, but the developer docs have https://blog.mozilla.org/thunderbird whereas thunderbird.net has https://blog.thunderbird.net/

**Comment by jobisoft** [comment]
That is not in the source files but in some gitbook config? Ryan, can you help?

**Comment by ryanleesipes** [comment]
They both direct to the same place. But I have updated the link to blog.thunderbird.net, thank you for bringing that to my attention @camporter - it is good just so that in case the redirect is ever shut off everything keeps working!
