### ISSUE TITLE
Update docs to reflect removal of legacy add-on support

### ISSUE THREAD

**Issue by PaulMorris** [thundernest/developer-docs#59]
Now that calendar is close to being integrated into TB (https://bugzilla.mozilla.org/show_bug.cgi?id=1608610), it is my understanding that support for legacy extensions will be going away soon after, possibly as soon as the next TB beta that will be released after the Firefox 73 merge on Feb 10 (https://wiki.mozilla.org/Release_Management/Calendar).  The docs should help add-on devs understand and prepare for this.  Here are a few things we can do.  There are probably others as well.

- Mail/WebExtensions Experiments should be more prominent, for example a brief description and link to further docs on the "About Add-ons" page (like what's currently on the "Updating Legacy Extensions for Thunderbird 78" page).

- On the "About Add-ons" page there should be a stronger message that legacy extensions are deprecated, with support soon to be removed, with a mention of approximately when they are going away.

**Comment by clokep** [comment]
@PaulMorris We should probably make sure to announce this on the appropriate mailing lists too!

**Comment by jobisoft** [comment]
I started to work on a re-ordering of the addons section a couple of weeks back, but it was too much for me. The draft is still in gitbook but I think no longer merge-able, as so much has changed in between. 

I do believe, that we should seperate core dev and addon dev more obviously as it is done now. So if you start to shift things around, maybe have that in mind as well?

**Comment by PaulMorris** [comment]
@clokep Good call.  I have just sent an email to tb-planning and the TB addons lists.  
@jobisoft Is there somewhere I can see your draft work on a re-ordering?  I'd like to at least see where you were going with it, in case I find time to work on this.

**Comment by jobisoft** [comment]
@PaulMorris : You need to log into gitbook. Ryan can give you access if you do not have that.

![grafik](https://user-images.githubusercontent.com/5830621/73588706-9ca07500-44cc-11ea-973b-a15bb724a463.png)

In the top left you should see my draft under "edits".

**Comment by jobisoft** [comment]
@PaulMorris : My main idea was to have only two main sections (core and addon). I do not think it is mergeable, as so much changed in the core section and i do not know if gitbook can cope with those when I moved everything around.

**Comment by jobisoft** [comment]
@PaulMorris : My draft is actually loaded in the screenshoot above, so you can see my concept there already.

**Comment by PaulMorris** [comment]
Thanks @jobisoft , that's helpful.  I'm going to work on this now.  Probably won't get into the re-arranging, just the updates to the addons info.

**Comment by jobisoft** [comment]
We forgot to close this. DTN has been updated.
