### ISSUE TITLE
Migrate the Chat Core section from MDN

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/developer-docs#68]
We should migrate the Chat Core section from MDN, and all its subsections, to DTN.
https://developer.mozilla.org/en-US/docs/Mozilla/Chat_Core

**Comment by freaktechnik** [comment]
@clokep I think this is done now, right?

**Comment by clokep** [comment]
It is! I didn't realize an issue had gotten filed! 🎉 

You can find the updated docs at https://developer.thunderbird.net/thunderbird-development/codebase-overview/chat

(I can't seem to close issues on this repo so whoever can please close this!)
