### ISSUE TITLE
Images not visible on developer.thunderbird.net

### ISSUE THREAD

**Issue by PaulMorris** [thundernest/developer-docs#78]
Images on these pages are not visible for me.  
https://developer.thunderbird.net/thunderbird-development/hello-world
https://developer.thunderbird.net/thunderbird-development/building-thunderbird/artifact-builds
The Thunderbird logo is also not visible in the site header.  Instead of the images I see a "missing image" placeholder.  The console reports CORS issues like this:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gstatic.gitbook.com/js/111.e4f7ad42.js. (Reason: CORS request did not succeed).
```

**Comment by PaulMorris** [comment]
Well, it works for me on chromium, but not on firefox.  Two others reported that it works fine for them.  So it may just be something weird with my firefox.

**Comment by Sancus** [comment]
I'd double check with add-ons disabled as a start. Other than that, not totally sure what could be interfering with this.

**Comment by PaulMorris** [comment]
I think we can close this.  I haven't noticed it recently.
