### ISSUE TITLE
Link to documentation for parseXULToFragment() is dead

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#85]
[Here](https://github.com/thundernest/developer-docs/blob/master/add-ons/updating/tb78/changes.md) we have the following link: [parseXULToFragment()](https://github.com/cleidigh/ThunderStorm/blob/master/examples/MailExtensions/WindowListener/content/messenger.js#L22-L31). But - this link is dead.

**Comment by jobisoft** [comment]
updated
