### ISSUE TITLE
Do we still QI windows to nsIMsgWindow?

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#86]
On [this page](https://github.com/thundernest/developer-docs/blob/master/add-ons/updating/tb78/changes.md), it says:

> With TB70, window objects don't need to be and cannot be QI'ed to nsIDOMChromeWindow, nsIDOMWindow and nsIInterfaceRequestor. You can just remove its usage, this is backwards compatible to TB 68. See the fix applied to enigmail.

but what about other interfaces? e.g. nsIMsgWindow? Do we still need to QI for that? This should be clarified.

**Comment by jobisoft** [comment]
I disagree. It is a list of affected interfaces. We do not have to list all the interfaces which do not require this.

**Comment by jobisoft** [comment]
But it could of course be, that we missed an interface. If you find one, than we will of course add it to the list.

**Comment by eyalroz** [comment]
> We do not have to list all the interfaces which do not require this.

Indeed, but it's not clear that you haven't. The distinction between "no need to QI at all" and "some of the interfaces don't need QIing anymore, the rest do" is not clear enough.

**Comment by jobisoft** [comment]
In ESR60 and ESR68 I did not find any usage of QI(nsIMsgWindow):

https://searchfox.org/comm-esr68/search?q=QueryInterface\(.*nsIMsgWindow&path=&case=false&regexp=true

but a lot of QI(nsIDOMWindow) (so the query works):

https://searchfox.org/comm-esr68/search?q=QueryInterface\(.*nsIDOMWindow&path=&case=false&regexp=true

I tend to close this as irrelevant. If you can, please provide a code fragment where you had to QI to nsIMsgWindow so we can check if it is still possible/neeed.

**Comment by eyalroz** [comment]
I just suggested a phrasing tweak. But - ok.
