### ISSUE TITLE
TB 78 changes page should (?) suggest explicitly adding drop-markers to menubuttons

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#87]
JaneK recently wrote:

> One thing that apparently changed with toobarbuttons (type=menu or type=menu-button) is that you have to include the dropmarker as child of the button:
>
>    ```
> <toolbarbutton type="menu-button">
>   <menupopup ..>
>   ...
>   </menupopup>
>   <dropmarker type="menu-button" class="toolbarbutton-menubutton-dropmarker" />
> </toolbarbutton>
> ```
> I had a similar issue with a toolbarbutton that shows a menu.

**Comment by jobisoft** [comment]
The dropmarker does not need to be added manually. I think we solved this with the custom element, didn't we?

**Comment by eyalroz** [comment]
Yes, and without specifying a dropmarker. So closing.
