### ISSUE TITLE
TB 68->78 changes page should mention removal of nsIEditorStyleSheets

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#92]
The [removal of nsIEditorStyleSheets](https://bugzilla.mozilla.org/show_bug.cgi?id=1449522) necessitates the following changes:

* `addOverrideStyleSheet(uri)` -> `windowUtils.loadSheetUsingURIString(uri, windowUtils.AGENT_SHEET)`
* `removeOverrideStyleSheet(uri)` -> `windowUtils.removeSheet(uri, windowUtils.AGENT_SHEET)`
* `enableStyleSheet(uri, enable)` -> `(enable ? windowUtils.loadStyleSheetUsingURIString : windowUtils.removeSheet)(uri, windowUtils.AGENT_SHEET)`

The TB 68->78 changes page should mention this.

**Comment by jobisoft** [comment]
Thanks for working this out!

**Comment by eyalroz** [comment]
@jobisoft : I do believe you're the one who figured it out... :-)

**Comment by jobisoft** [comment]
done.
