### ISSUE TITLE
TB 68 -> 78 page should discuss removal of document.getAnonymousElementByAttribute()

### ISSUE THREAD

**Issue by eyalroz** [thundernest/developer-docs#94]
An important API function removed over the past year is [`document.getAnonymousElementByAttribute()`](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XBL/XBL_1.0_Reference/DOM_Interfaces).

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1591145

The TB 68->78 [changes pages](https://developer.thunderbird.net/add-ons/updating/tb78/changes) should discuss this and suggest an alternative.

**Comment by jobisoft** [comment]
That is part of the XBL removal which was done in TB68. This is currently above my head. What did you use it for?

**Comment by eyalroz** [comment]
It was part of this piece of code which tried several ways of getting the message subject, each of which worked with different versions of TB or SM. The removal happened in TB 72 according to the bug page.

**Comment by jobisoft** [comment]
This document which is linked in the TB68 guide has some info about this:
https://wiki.mozilla.org/Thunderbird/de-xbl

Is that sufficient?

**Comment by eyalroz** [comment]
@jobisoft : 

1. No, because extension authors don't use that method only for their own XBL elements. They may think of it as merely another DOM search utility.
2. Because this removal _is_ a 68->78 change.
3. Because, glancing at that document, it's not at all clear that this is a change to notice. The TB 68->78 changes page has a nice header with each removed API.

**Comment by jobisoft** [comment]
> It was part of this piece of code

Which code? Cabn you link?

**Comment by jobisoft** [comment]
I am not saying you are wrong. But it appears the removed function in TB72 was already "dead code" (always returned null pointer) so the functionality stopped long ago. With TB72 it would throw now that an unknown function has been used.

This is obviously a function related to XBL.

**Comment by eyalroz** [comment]
@jobisoft : [this](https://github.com/eyalroz/bidimailui/blob/master/src/chrome/content/bidimailpack/bidimailpack-messenger.js#L135). It was already failing in what it was trying to do in v68, but it didn't throw an exception. Also, it _was_ necessary/useful in earlier versions.

**Comment by jobisoft** [comment]
So my assumption is true :-)

Woohoo: A lot of add-ons are still using that:
https://github.com/search?q=getAnonymousElementByAttribute++path:/xall/x68+repo%3Acleidigh%2FThunderKdB&type=Code

So what did you use it for? Why not just use getElementById or something?

**Comment by eyalroz** [comment]
> So what did you use it for? Why not just use getElementById or something?

The field with the text used to be an anonymous element within the XBL subject box. So, I couldn't get it byId().

**Comment by jobisoft** [comment]
https://developer.thunderbird.net/add-ons/updating/tb78/changes#getanonymouselementbyattribute-and-getanonymousnodes-have-been-removed

I do not think there is more to say, is there?

**Comment by eyalroz** [comment]
> I do not think there is more to say, is there?

Well:

1. If this stopped working in TB 68, perhaps there needs to be a note about these in the TB 68 document.
2. The links you added are to the German version of the documentation.

**Comment by jobisoft** [comment]
1. I think it is, isn't it? There is a section about [Removed XBL bindings](https://developer.thunderbird.net/add-ons/updating/tb68/changes#removed-xbl-bindings) and there is a [linked document](https://wiki.mozilla.org/Thunderbird/de-xbl) which includes the removal/replacement of getAnonymousElementByAttribute

2. Thanks! That happens way to often. Fixed.

**Comment by eyalroz** [comment]
>     1. I think it is, isn't it? There is a section about [Removed XBL bindings](https://developer.thunderbird.net/add-ons/updating/tb68/changes#removed-xbl-bindings) and there is a [linked document](https://wiki.mozilla.org/Thunderbird/de-xbl) which includes the removal/replacement of getAnonymousElementByAttribute

But there is nothing inherently XBL'ish about a method named `getAnonymousElementByAttribute()`. When I was updating my extensions for TB 68 it didn't occur to me that to follow that link, since I as far as I was concerned, I wasn't using any XBL.

**Comment by mkmelin** [comment]
Maybe it's not apparent, but the whole concept of anonymous content is (was) XBL only.

**Comment by jobisoft** [comment]
Hm, the very first google search result of "MDN getAnonymousElementByAttribute()" returns:

https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XBL/XBL_1.0_Reference/DOM_Interfaces

which tells you this method belongs to the XBL stuff. I hesitate to duplicate the information ...

**Comment by eyalroz** [comment]
> I hesitate to duplicate the information ...

There's no problem with a bit of duplication between the 78-changes page and other pages which describe these changes in a different context.  But it's your call I guess.

**Comment by jobisoft** [comment]
We are talking about duplication inside the TB68 add-on guide. I did add the info to the TB78 guide, as it throws errors now. 

Let me sleep over this. I probably extend the info box in the TB68 guide.

**Comment by jobisoft** [comment]
https://developer.thunderbird.net/add-ons/updating/tb68/changes#removed-xbl-bindings

**Comment by eyalroz** [comment]
I can live with that.
